version: '2'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - mynet
  rest:
    image: go-url-server
    ports: 
      - 8000:8000
    networks:
      - mynet
    
networks:
  mynet:
    driver: bridge